language: ruby
rvm: 2.2.7
sudo: false
matrix:
  include:
    - rvm: ruby-3.0.0-rc1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

services:
  - postgresql
  - mysql
  - redis-server

before_install:
  - gem install bundler
  - psql -c 'create database ci_test;' -U postgres
  - mysql -e 'create database if not exists ci_test;'

script:
  - gem list -l
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori-contrib.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
